INSERT INTO `vue-project`.`todos` (`title`, `completed`) VALUES
("Find a use for Slots and Mixins",1),
("Find difference between Vue Watchers and computed",1),
("Find a use for a watcher",1),
("Create a custom event with $emit",1),
("Find a use for nextTick",0),
("Refactor ifs in form vues",1),
("Use custom style binding :style=",0),
("Export titleState and titleValid to module file",0),
("Test out git branches and merging",0),
("Research Server side rendering and Nuxt- basics",0),
("Brush up on SOLID",0),
("Research JWT",0),
("Implement a service worker",0),
("Research docker basics",1),
("Make To-Do's save to database",0),
("Create content-box",1),
("Research @NoRepositoryBean",0);